<div><div ng-controller="analyticsCtrl">
        <form role="form" action="/sim/analytics" class="form-horizontal" method="POST" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-10">
                            <div class="form-group">
                                <label for="existingMetaProfile" class="col-md-6 control-label">Meta Skeleton Profiles</label>
                                <div class="col-md-6">
                                    <select class="form-control"  id="existingMetaProfile" name="existingMetaProfile" ng-model="existingMetaProfileLeft" ng-options="c.name for c in existingMetaProfileOptions">
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row xaxis-params">
                        <!--Skelition Parameters Block-->
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label for="xaxisparamsleft" class="col-md-4 control-label">X-axis Parameter</label>
                                <div class="col-md-8">
                                    <select class="form-control" id="xaxisparamsleft" placeholder="X- axis parameters">
                                        <option value="-1">Please select...</option>
                                        <option value="MPIRanksperNode">MPI Ranks per Node</option>
                                        <option value="FanIn">Fan In</option>
                                        <option value="CoresperNode">Cores per Node</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label for="range" class="col-md-4 control-label">Range:</label>
                                <div class="col-md-8">
                                    <label for="rangestartleft" class="col-md-2 control-label">From</label>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="rangestartleft" placeholder="#" value="">
                                    </div>

                                    <label for="rangeendleft" class="col-md-2 control-label">To</label>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="rangeendleft" placeholder="#" value="">
                                    </div>

                                    <label for="rangestepleft" class="col-md-2 control-label">Step</label>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="rangestepleft" placeholder="#" value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--End of Skeleton Parameters Block-->
                    </div>
                    <div class="row yaxis-params">
                        <div class ="row">
                            <div class="form-group col-md-12">
                                <label for="yaxisparamsleft" class="col-md-4 control-label">Y-axis Parameter</label>
                                <div class="col-md-8">
                                    <select class="form-control" id="yaxisparamsleft" placeholder="Y- axis parameters">
                                        <option  value="0">Please select...</option>
                                        <option value="PercentageLocalCommunication">Percentage Local Communication</option>
                                        <option value="PercentageEnergyforCommunication">Percentage Energy for Communication</option>
                                        <option value="TotalEnergy">Total Energy</option>
                                        <option value="AverageTotalPower">Average Total Power</option>
                                        <option value="AveragePowerperNode">Average Power per Node</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class ="row"><!--Start of User Action Params-->
                        <div class="form-group">
                            <div class="col-md-4 col-md-offset-4">
                                <input type="button" id="submitbutton" name="submitbutton"  ng-click="plotgraph('left')" class="btn btn-success" value="Plot graph" />
                                <img src="/img/ajax-loader.gif" class="loading-indicator" id="loadingleft"  style="display: none"/>
                            </div>
                        </div>
                    </div><!--End of User Action Params-->
                    <div class="row">           <!-- Start of Results Section-->
                        <div class="col-md-12">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <h3 class="panel-title">Results</h3>
                            </div>
                            <div class="panel-body">
                                <div id="chart_divleft" style="width: 440px; height: 340px;"></div>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-10">
                            <div class="form-group">
                                <label for="existingMetaProfileRight" class="col-md-6 control-label">Meta Skeleton Profiles</label>
                                <div class="col-md-6">
                                    <select class="form-control"  id="existingMetaProfileRight" name="existingMetaProfileRight" ng-model="existingMetaProfileRight" ng-options="c.name for c in existingMetaProfileOptions">
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row xaxis-params">
                        <!--Skelition Parameters Block-->
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label for="xaxisparamsright" class="col-md-4 control-label">X-axis Parameter</label>
                                <div class="col-md-8">
                                    <select class="form-control" id="xaxisparamsright" placeholder="X- axis parameters">
                                        <option   value="0">Please select...</option>
                                        <option value="MPIRanksperNode">MPI Ranks per Node</option>
                                        <option value="FanIn">Fan In</option>
                                        <option value="CoresperNode">Cores per Node</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label for="range" class="col-md-4 control-label">Range:</label>
                                <div class="col-md-8">
                                    <label for="rangestartright" class="col-md-2 control-label">From</label>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="rangestartright" placeholder="#" >
                                    </div>

                                    <label for="rangeendright" class="col-md-2 control-label">To</label>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="rangeendright" placeholder="#" >
                                    </div>

                                    <label for="rangestepright" class="col-md-2 control-label">Step</label>
                                    <div class="col-md-4">
                                        <input type="text" class="form-control" id="rangestepright" placeholder="#" >
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--End of Skeleton Parameters Block-->
                    </div>
                    <div class="row yaxis-params">
                        <div class ="row">
                            <div class="form-group col-md-12">
                                <label for="yaxisparamsright" class="col-md-4 control-label">Y-axis Parameter</label>
                                <div class="col-md-8">
                                    <select class="form-control" id="yaxisparamsright" placeholder="Y- axis parameters">
                                        <option  value="0">Please select...</option>
                                        <option value="PercentageLocalCommunication">Percentage Local Communication</option>
                                        <option value="PercentageEnergyforCommunication">Percentage Energy for Communication</option>
                                        <option value="TotalEnergy">Total Energy</option>
                                        <option value="AverageTotalPower">Average Total Power</option>
                                        <option value="AveragePowerperNode">Average Power per Node</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class ="row"><!--Start of User Action Params-->
                        <div class="form-group">
                            <div class="col-md-4 col-md-offset-4">
                                <input type="button" id="submitbutton" name="submitbutton"  ng-click="plotgraph('right')" class="btn btn-success" value="Plot graph" />
                                <img src="/img/ajax-loader.gif" class="loading-indicator" id="loadingright" style="display: none" />
                            </div>
                        </div>
                    </div><!--End of User Action Params-->
                    <div class="row">           <!-- Start of Results Section-->
                        <div class="col-md-12">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <h3 class="panel-title">Results</h3>
                            </div>
                            <div class="panel-body">
                                <div id="chart_divright" style="width: 440px; height: 340px;"></div>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End of Results Section-->
        </form>
    </div>
</div>