<div>

    <div ng-controller="paramsCtrl">

        <form role="form" id="simulationform" action="" class="form-horizontal" method="POST" enctype="multipart/form-data">

            <div class="row">
                <div class="col-md-6 col-md-offset-2">
                    <div class="form-group">
                        <label for="existingMetaProfile" class="col-md-6 control-label">Meta Skeleton Profiles</label>
                        <div class="col-md-6">
                            <select class="form-control"  id="existingMetaProfile" name="existingMetaProfile" ng-model="existingMetaProfile" ng-change="updateProfile()" ng-options="c.name for c in existingMetaProfileOptions">
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row panel-padding">          <!--Skelition Parameters Block-->
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title">Skeleton Parameters</h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-group col-md-6">
                            <label for="analyticsWorkflow" class="col-md-4 control-label">Analytics Workflow</label>
                            <div class="col-md-8">
                                <select class="form-control"  id="analyticsWorkflow" name="analyticsWorkflow" ng-model="analyticsWorkflow" ng-options="c.name for c in analyticsWorkflowOptions">
                                </select>
                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="dataAnalyticsType" class="col-md-4 control-label">Data Analytics Type</label>
                            <div class="col-md-8">
                                <select class="form-control" id="dataAnalyticsType" name="dataAnalyticsType" ng-model="dataAnalyticsType" ng-options="c.name for c in dataAnalyticsTypeOptions">
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!--End of Skeleton Parameters Block-->

            <div class="row">
                <div class="col-sm-4 panel-padding"> <!--Architecture Parameters Block-->
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <div class="panel-title">Architecture Parameters 
                                <a data-toggle="modal" href="#archModel" class="btn btn-default btn-xs pull-right"><span class="glyphicon glyphicon-plus icon-success"></span></a>
                            </div>
                        </div>
                        <div class="panel-body panel-scroll">                         
                            <div class="form-group" ng-repeat="param in archParams">
                                <label for="{{param.name}}" class="col-lg-6 control-label">{{param.label}}</label>
                                <div class="col-lg-6" ng-if="param.type == 'text'">
                                    <div class="input-group"> 
                                        <input type="{{param.type}}" class="form-control" id="{{param.name}}" name="{{param.name}}" ng-model="param.value" placeholder="#">
                                        <span class="input-group-addon" ng-click="removeArchParam(param)">
                                            <span class="glyphicon glyphicon-remove" ></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-lg-6" ng-if="param.type == 'radio'">
                                    <label class="" ng-repeat="option in param.options">
                                        <input type="{{param.type}}" name="{{param.name}}" id="{{param.name}}" ng-model="param.value" value="{{option.name}}"> {{option.name}}
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>


                </div><!--End of Architecture Parameters-->
                <div class="col-sm-4 panel-padding">            <!--Start of Runtime Params-->
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <div class="panel-title">Runtime Parameters
                                <a data-toggle="modal" href="#runtimeModel" class="btn btn-default btn-xs pull-right"><span class="glyphicon glyphicon-plus icon-success"></span></a>
                            </div>
                        </div>
                        <div class="panel-body panel-scroll">
                            <div class="form-group" ng-repeat="param in runtimeParams">
                                <label for="{{param.name}}" class="col-lg-6 control-label">{{param.label}}</label>
                                <div class="col-lg-6" ng-if="param.type == 'text'">
                                    <div class="input-group">
                                        <input type="{{param.type}}" value="0" class="form-control" id="{{param.name}}" name="{{param.name}}" ng-model="param.value" placeholder="#">
                                        <span class="input-group-addon" >
                                            <span class="glyphicon glyphicon-remove" ng-click="removeCoDesignParam(param)"></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-lg-6" ng-if="param.type == 'radio'">
                                    <label class="" ng-repeat="option in param.options">
                                        <input type="{{param.type}}" name="{{param.name}}" id="{{param.name}}" ng-model="param.value" value="{{option.name}}"> {{option.name}}
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>

                </div><!--End of Runtime Parameters-->
                <div class="col-sm-4 panel-padding"> <!--Start of Application Params-->
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <div class="panel-title">Application Parameters
                                <a data-toggle="modal" href="#appModel" class="btn btn-default btn-xs pull-right"><span class="glyphicon glyphicon-plus icon-success"></span></a>
                            </div>
                        </div>
                        <div class="panel-body panel-scroll">
                            <div class="form-group" ng-repeat="param in appParams">
                                <label for="{{param.name}}" class="col-lg-6 control-label">{{param.label}}</label>
                                <div class="col-lg-6">
                                    <div class="input-group">
                                        <input type="{{param.type}}" value="0" class="form-control" id="{{param.name}}" name="{{param.name}}" ng-model="param.value" placeholder="#">
                                        <span class="input-group-addon" >
                                            <span class="glyphicon glyphicon-remove" ng-click="removeAppParam(param)"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="mpiActivityFile" class="col-lg-6 control-label">MPI Activity File</label>
                                <div class="col-lg-6">
                                    <div class="input-group">
                                        <input type="file" id="mpiActivityFile" name="mpiActivityFile" ng-model="mpiActivityFile">
                                        <p class="help-block">(Source_MPI_Rank, Destination_MPI_Rank, data_size)</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-offset-6">

                            </div>
                        </div>
                    </div><!--End of Application Parameter-->
                </div>

                <div class ="row"><!--Start of User Action Params-->
                    <div class="form-group">
                        <div class="col-md-3 col-md-offset-5">
                            <input type="button" class="btn btn-success" value="Simulate" ng-click="simulate()">
                            <input type="button" class="btn btn-success" value="Save" ng-click="save()"/>
                            <a data-toggle="modal" href="#saveasModel" class="btn btn-success"><span class="">Save As</span></a>
                        </div>
                        <div class="col-md-4 success">
                            {{opmessage}}
                        </div>  
                        
                    </div>
                </div><!--End of User Action Params-->
            </div>
        </form>
        <div class="row">           <!-- Start of Results Section-->
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Results</h3>
                </div>
                <div class="panel-body">
                    <div class="simulationResult"></div>
                </div>

            </div>
        </div><!--End of Results Section-->

        <div class="modal fade" id="archModel" tabindex="-1" role="dialog" aria-labelledby="myModelLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">New Architecture Parameter</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="newArchLabel" class="col-lg-6 control-label">New Parameter Label : </label>
                            <div class="col-lg-6">
                                <input type="newArchLabel" ng-model="newArchLabel"  id="newArchLabel" name="newArchLabel" placeholder="">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" ng-click="addArchParam()">Save changes</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="runtimeModel" tabindex="-1" role="dialog" aria-labelledby="myModelLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">New Runtime Parameter</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="newruntimeLabel" class="col-lg-6 control-label">New Parameter Label : </label>
                            <div class="col-lg-6">
                                <input type="newruntimeLabel" ng-model="newruntimeLabel"  id="newArchLabel" name="newruntimeLabel" placeholder="">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" ng-click="addCoDesignParam()">Save changes</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="appModel" tabindex="-1" role="dialog" aria-labelledby="myModelLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">New Application Parameter</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="newAppLabel" class="col-lg-6 control-label">New Parameter Label : </label>
                            <div class="col-lg-6">
                                <input type="newAppLabel" ng-model="newAppLabel"  id="newArchLabel" name="newAppLabel" placeholder="">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" ng-click="addAppParam()">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="saveasModel" tabindex="-1" role="dialog" aria-labelledby="myModelLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">New Meta Skeleton Profile</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="newskeletonName" class="col-lg-6 control-label">New Meta Skeleton Profile Name: </label>
                            <div class="col-lg-6">
                                <input type="newskeletonName" ng-model="newskeletonName"  id="newskeletonName" name="newskeletonName" placeholder="">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" ng-click="saveas()">Save changes</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>