<div  >

    <div class="">

        <form role="form" class="form-horizontal" method="POST">

            <div class="row">
                <div class="col-md-6 col-md-offset-2">
                    <div class="form-group">
                        <label for="existingMetaProfile" class="col-md-6 control-label">Use Existing Meta-profiles</label>
                        <div class="col-md-6">
                            <select class="form-control"  id="existingMetaProfile" name="existingMetaProfile" placeholder="Existing Profiles">
                                <option value="0">Please select...</option>
                                <option selected value="Titan">Titan</option>
                                <option value="Create New Profile">Create New Profile</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row panel-padding">          <!--Skelition Parameters Block-->
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title">Skeleton Parameters</h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-group col-md-6">
                            <label for="analyticsWorkflow" class="col-md-4 control-label">Analytics Workflow</label>
                            <div class="col-md-8">
                                <select class="form-control"  id="analyticsWorkflow" name="analyticsWorkflow" placeholder="Analytics Workflow">
                                    <option value="0">Please select...</option>
                                    <option selected value="Toplogy analytics">Topology analytics</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="dataAnalyticsType" class="col-md-4 control-label">Data Analytics Type</label>
                            <div class="col-md-8">
                                <select class="form-control" id="dataAnalyticsType" name="dataAnalyticsType" placeholder="Data Analytics Type">
                                    <option value="0">Please select...</option>
                                    <option selected value="In-situ">In-situ</option>
                                    <option disabled="" value="2">In-transit</option>
                                    <option disabled="" value="3">Hybrid</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!--End of Skeleton Parameters Block-->

            <div class="row">
                <div class="col-sm-4 panel-padding" ng-controller="archCtrl"> <!--Architecture Parameters Block-->
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <h3 class="panel-title">Architecture Parameters</h3>
                        </div>
                        <div class="panel-body panel-scroll">                         
                            <div class="form-group" ng-repeat="param in archParams">
                                <label for="{{param.name}}" class="col-lg-6 control-label">{{param.label}}</label>
                                <div class="col-lg-6">
                                    <div class="input-group">
                                        <input type="{{param.type}}" value="0" class="form-control" id="{{param.name}}" name="{{param.name}}" placeholder="#">
                                        <span class="input-group-addon" ng-click="remove($event)">
                                            <span class="glyphicon glyphicon-remove" ></span>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group ">
                                <label for="networkType" class="col-lg-6 control-label">Network Type</label>
                                <div class="col-lg-6">
                                    <label class="">
                                        <input type="radio" selected name="networkType" id="networkType" value="Gemini"> Gemini
                                    </label>
                                    <label class="">
                                        <input type="radio" name="networkType" id="networkType" value="Gemini"> Infiniband
                                    </label>
                                </div>
                            </div>
                            <div class="col-md-offset-6">
                                <a data-toggle="modal" href="#archModel" class="btn btn-default">Add <span class="glyphicon glyphicon-plus icon-success"></span></a>
                            </div>
                        </div>
                    </div>


                </div><!--End of Architecture Parameters-->
                <div class="col-sm-4 panel-padding" ng-controller="codesignCtrl">            <!--Start of Coddesign Params-->
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <h3 class="panel-title">Co-design Parameters</h3>
                        </div>
                        <div class="panel-body panel-scroll">
                            <div class="form-group" ng-repeat="param in codesignParams">
                                <label for="{{param.name}}" class="col-lg-6 control-label">{{param.label}}</label>
                                <div class="col-lg-6">
                                    <div class="input-group">
                                        <input type="{{param.type}}" value="0" class="form-control" id="{{param.name}}" name="{{param.name}}" placeholder="#">
                                        <span class="input-group-addon" >
                                            <span class="glyphicon glyphicon-remove" ng-click="remove($event)"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="mpiRankMappingPolicy" class="col-lg-6 control-label">MPI rank mapping Policy</label>
                                <div class="col-lg-6">
                                    <label class="">
                                        <input type="radio" name="mpiRankMappingPolicy" id="mpiRankMappingPolicy" value="Consecutive"> Consecutive
                                    </label>
                                    <label class="">
                                        <input type="radio" name="mpiRankMappingPolicy" id="mpiRankMappingPolicy" value="Random"> Random
                                    </label>
                                </div>
                            </div>
                            <div class="col-md-offset-6">
                                <a data-toggle="modal" href="#codesignModel" class="btn btn-default">Add <span class="glyphicon glyphicon-plus icon-success"></span></a>
                            </div>
                        </div>
                    </div>

                </div><!--End of Co-design Parameters-->
                <div class="col-sm-4 panel-padding" ng-controller="appCtrl"> <!--Start of Application Params-->
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            <h3 class="panel-title">Application Parameters</h3>
                        </div>
                        <div class="panel-body panel-scroll">
                            <div class="form-group" ng-repeat="param in appParams">
                                <label for="{{param.name}}" class="col-lg-6 control-label">{{param.label}}</label>
                                <div class="col-lg-6">
                                    <div class="input-group">
                                        <input type="{{param.type}}" value="0" class="form-control" id="{{param.name}}" name="{{param.name}}" placeholder="#">
                                        <span class="input-group-addon" >
                                            <span class="glyphicon glyphicon-remove" ng-click="remove($event)"></span>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="mpiActivityFile" class="col-lg-6 control-label">MPI Activity File</label>
                                <div class="col-lg-6">
                                    <div class="input-group">
                                        <input type="file" id="mpiActivityFile" name="mpiActivityFile">
                                        <p class="help-block">(Source_MPI_Rank, Destination_MPI_Rank, data_size)</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-offset-6">
                                <a data-toggle="modal" href="#appModel" class="btn btn-default">Add <span class="glyphicon glyphicon-plus icon-success"></span></a>
                            </div>
                        </div>
                    </div><!--End of Application Parameter-->
                </div>

                <div class ="row"><!--Start of User Action Params-->
                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-5">
                            <input type="submit" class="btn btn-success" value="Save & Process" />
                            <input type="submit" class="btn btn-success" value="Process"/>
                        </div>
                    </div>
                </div><!--End of User Action Params-->


            </div>
        </form>

        <div class="row">           <!-- Start of Results Section-->
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Results</h3>
                </div>
                <div class="panel-body">
                    <?php echo $message ?>
                    <table>
                        <tr>
                            <th>Parameter</th>
                            <th>Value</th>
                        </tr>
                        <?php
                        foreach ($rawBody as $key => $value) {
                            ?>
                            <tr>
                                <td><?= $key ?></td>
                                <td><?= $value ?></td>
                            </tr>     
                        <?php }
                        ?>
                    </table>
                </div>

            </div>
        </div><!--End of Results Section-->

        <div class="modal fade" id="archModel" tabindex="-1" role="dialog" aria-labelledby="myModelLabel" aria-hidden="true" ng-controller="archCtrl">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">New Architecture Parameter</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="newArchLabel" class="col-lg-6 control-label">New Parameter Label : </label>
                            <div class="col-lg-6">
                                <input type="newArchLabel" ng-model="newArchLabel"  id="newArchLabel" name="newArchLabel" placeholder="">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" ng-click="add($event)">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="modal fade" id="codesignModel" tabindex="-1" role="dialog" aria-labelledby="myModelLabel" aria-hidden="true" ng-controller="codesignCtrl">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">New Co-Design Parameter</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="newcodesignLabel" class="col-lg-6 control-label">New Parameter Label : </label>
                            <div class="col-lg-6">
                                <input type="newcodesignLabel" ng-model="newcodesignLabel"  id="newArchLabel" name="newcodesignLabel" placeholder="">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" ng-click="add($event)">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="modal fade" id="appModel" tabindex="-1" role="dialog" aria-labelledby="myModelLabel" aria-hidden="true" ng-controller="appCtrl">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">New Application Parameter</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="newAppLabel" class="col-lg-6 control-label">New Parameter Label : </label>
                            <div class="col-lg-6">
                                <input type="newAppLabel" ng-model="newAppLabel"  id="newArchLabel" name="newAppLabel" placeholder="">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" ng-click="add($event)">Save changes</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>